# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  pathtosolution: 'PizzaBoxMVC_20190603_2041'
  pathtoproject: 'PizzaBoxMVC_20190603_2041/PizzaBoxWebApp'
  buildConfiguration: 'Release'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: $(pathtosolution)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(pathtoproject)/*.csproj'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(97d19032-7efb-4f95-b493-6e2c8f0a5ef7)'
    appType: 'webApp'
    appName: 'PizzaBoxWebApp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

